language: go
go:
- 1.14.x
- 1.15.x
cache:
  directories:
  - "${GOPATH}/pkg/mod"
  - "${GOPATH}/pkg/sumdb"
env:
  global:
  - GO111MODULE: 'on'
before_script:
- |
  (
    cd
    go get \
      gotest.tools/gotestsum \
      github.com/golangci/golangci-lint/cmd/golangci-lint@v1.33.0
  )
script:
- scripts/check
- scripts/test
