language: go
go:
  - '1.10.x'
  - '1.11.x'
script:
  - go test -v ./...
jobs:
  include:
    - stage: deploy
      deploy:
        provider: script
        skip_cleanup: true
        script: npx semantic-release
